### ISSUE TITLE
Do you have support for Windows?

### ISSUE THREAD

**Issue by solopromiguel** [bozhink/ThermalPrinterDotNetCore#1]
Hi, thanks for the input, I need to implement it in a windows environment but I see that it uses commands for linux "/ dev / usb / lp1"

How can I use it for windows 7 onwards? thanks

**Comment by bozhink** [comment]
Hi,

For use in Windows you can open SerialPort:

1. Add package reference to System.IO and System.IO.Ports
2. Instead of `var stream = new FileStream("/dev/usb/lp1", FileMode.Open, FileAccess.Write)` you shoud use something like
```c#
var serialPort = new SerialPort("COM1", 9200, Parity.None, 8);
serialPort.Open();

var stream = serialPort.BaseStream;
```

If you need network-connected printer, try something like
```c#
var printerUri = new Uri("printer uri");

var tcpClient = new TcpClient();
tcpClient.Connect(printerUri.Host, printerUri.Port);

var stream = tcpClient.GetStream();
```

If you have USB-connected printer try with mapping of the USB to virtual COM-port (this should be provided in the drivers of the printer). Same for bluetooth-connected printer.
